### ISSUE TITLE
Impossible to safely use set_state_callback with context

### ISSUE THREAD

**Issue by jD91mZM2** [jnqnfe/pulse-binding-rust#19]
`set_state_callback` does not (unlike the C library) supply the Context as a parameter to the closure. That leaves us with passing the Context using an Rc+RefCell to the closure. Which fails at runtime, since the `connect` function takes a mutable reference which makes it borrowed twice at the same time when used inside the closure.

**Comment by jnqnfe** [comment]
I'll have a look later to refresh my mind on the relevant components here, but speaking of `Rc`, are you aware of `Arc`, the thread-safe version, which might simply be what you're missing here :)

**Comment by jnqnfe** [comment]
Right, so `Rc`+`RefCell` is indeed the right way to go, and it is totally safe, so long as you're doing things right, i.e. you're correctly using the mainloop lock.

It all comes down to *when* callbacks get executed and control over their execution with the threaded mainloop lock.

Callbacks are only executed by the mainloop, and the mainloop only runs when you are not holding the lock! Thus, when we clone the context in creating the state callback, the mainloop has not actually been started yet, so the callback can't run yet, so only one mutable copy of the context is active. We then start the mainloop and start testing the state waiting for it to be ready. As we do so, we use locking, which ensures that when we check the state, we know for certain that our context is the only active one, whereas when we release the lock (note that wait() automatically releases then re-obtains the lock), we know that only the callback is possibly running. We therefore know that only one of our context instances is in use at any one time.

See the large example at the bottom of the `::mainloop::threaded` mod for an example implementation.

**Comment by jD91mZM2** [comment]
Sorry, yes, you're right you can *safely* do it, but you can't `safe`ly... As in without using `unsafe` :stuck_out_tongue_closed_eyes:. If possible, it would be great to let the callback pass the context as an argument, like the underlying PulseAudio C API (though maybe that introduces some *actual* unsafety, I'm not sure).

Though your example did teach me about `as_ptr` on RefCell, which I did not know existed. That's slightly easier, even though I wish it was possible 100% without unsafe.
```rust
        context.borrow_mut().set_state_callback(Some(Box::new(move || {
            let state = unsafe { (*context_ref.as_ptr()).get_state() };
```

Thanks for this crate by the way, I have used the `libpulse_sys` crate for a while, and am now converting to `libpulse_binding` :)

**Comment by jnqnfe** [comment]
> Sorry, yes, you're right you can _safely_ do it, but you can't `safe`ly... As in without using `unsafe` stuck_out_tongue_closed_eyes. If possible, it would be great to let the callback pass the context as an argument, like the underlying PulseAudio C API (though maybe that introduces some _actual_ unsafety, I'm not sure).
> 
> Though your example did teach me about `as_ptr` on RefCell, which I did not know existed. That's slightly easier, even though I wish it was possible 100% without unsafe.

I can't remember why exactly it was that I chose not to pass it along, but I know it was a deliberate choice. I'll perhaps take another look at some point to re-evaluate.

I wouldn't get too hung up on worrying about completely avoiding use of `unsafe` blocks in your code, I was the same when I started with Rust, but you've got to learnt to relax about it and accept that they are perfectly acceptable in odd places where you need to, and know for certain that it is safe to, override the general safety check. The blanket default protection catches most problems, and gives assurance that all code not within `unsafe` blocks should conform to a certain standard of safety, but the compiler is not perfect, and `unsafe` is there to allow you as the programmer to override it when needed; don't think of `unsafe` highlighting things that are unsafe, it is for blocks where you yourself are taking control and giving assurance that what happens within is safe.

> Thanks for this crate by the way, I have used the `libpulse_sys` crate for a while, and am now converting to `libpulse_binding` :)

No problem :)

**Comment by lukasjuhrich** [comment]
I'm neither an expert in rust nor in Pulse's API, but this argumentation is very confusing to me.
Even if we agree that `unsafe` blocks may not be that bad – isn't trying to bind the argument in the closure still the more complicated solution? The function is literally there to react to state changes with the context, so very frequently it e.g. will want to look things up in it. Isn't that the reason why the actual C API supports a context argument? And passing mutable reference to something in a closure while you're using it afterwards just feels like the wrong way to go, so it's kinda weird to me to assume that people using this crate (who aren't necessarily experts) will naturally find this workaround and to just close this issue.

Another disadvantage of deviating from the API in that way is that the C examples of how to use the pulse API become a bit useless because they all make heavy use of the `context` as the first parameter (e.g. [pavucontrol](context_state_callb)).

My use case is just gathering some configurational info, so I don't even want to do anything with the mainloop afterwards and instead just print out things on the `READY` state change. I didn't manage to get it to work though when I tried to extract the closure to a separate function, so sorry for being a bit frustrated.

**Comment by jnqnfe** [comment]
> I'm neither an expert in rust nor in Pulse's API, but this argumentation is very confusing to me.
> Even if we agree that `unsafe` blocks may not be that bad – isn't trying to bind the argument in the closure still the more complicated solution? The function is literally there to react to state changes with the context, so very frequently it e.g. will want to look things up in it. Isn't that the reason why the actual C API supports a context argument?...

It is certainly messier and more complicated for users than just providing a context object as a param, but there are complications to consider. If the binding takes the context pointer provided to the underlying C callback, and then wraps that in a nice binding layer wrapper which it then gives to the callback (I'm sure that it would be necessary to pass ownership rather than a reference), then:
 1. We need to ensure that when the execution of the callback ends, the destruction of the wrapper object does not cause destruction of the underlying C object, unlike with usual destruction of the wrapper type. The wrapper actually has a hidden internal "weak" attribute which the code setting things up could use to address this problem, but then there's a secondary issue of use-after-free with respect to possible early destruction of the primary context wrapper object while the callback one may still exist and may still be run. Alternatively a non-weak context object could be constructed by incrementing the underlying counter. So there is a good solution available in this case.
 2. We then have two entirely detached context objects, which could be used in ways that completely escape borrow checking since the borrow checker has no idea that they are related. Use of this secondary object may not actually be confined to the callback, since there's nothing to prevent users moving it outside of the callback somewhere, thus it's creation means potential for users to wreak all kinds of havoc. This would not be a problem if only a reference were provided to the callback, but I don't think that would be possible. We can't practically create a special object with a more limited set of functionality to the proper context wrapper type since we'd then have to duplicate so much of the context wrapper interface in terms of all the functions it needs to have; that doesn't fully solve it anyway; we don't necessarily want some of those limitations; and we'd possibly have to do this for other objects also, which just makes a huge mess.
 3. Additionally, the wrapper stores ("owns") certain components of "multi-use callbacks" as part of allowing such things to work with the closure based design. If users try to set a callback with such a new context wrapper object within a callback, those components are then being saved in a context wrapper object that is about to be destroyed (at the end of the callback), so then we're in a right mess since the new callback setup has been broken with a use-after-free situation. Again, to go back a moment to the previous item, with an alternate more limited wrapper type for callbacks we could block callback creation thus this would not be an issue, but that's not necessarily what we really want, besides the other aspects.

Possibly the only half decent solution that would allow a context param and not be affected by these issues would be for the methods setting up callbacks to take either an owned `Rc<Self>` or a reference to one, rather than a pure reference to self, such that a clone of the `Rc` wrapper object can be passed in. But this is undesirable for reasons including that it goes against basic method design, it makes use of the methods much messier, and it blocks users from using `Arc` instead of `Rc` if they wanted/needed to for some reason.

All of these issues are simply not a problem with the current design of requiring users to wrap their main context object in `Rc` and give a clone to the callback. The little bit of `unsafe` pointer hack ugliness with that is better than having to cope with or worry about those problems in my opinion.

> And passing mutable reference to something in a closure while you're using it afterwards just feels like the wrong way to go...

Wiring up a nice binding up to the PulseAudio C API is difficult. There are complications here and there that force compromises. Hopefully in the future when I've found both the time and a path through the difficult details for switching to futures, things will be cleaner. But this is not certain, and I can't think off hand whether you'd not still need `Rc`/`Arc`/whatever wrappers and the same ugliness anyway. It may not be possible to properly address existing ugly details or even properly switch to futures without changes to the PulseAudio C API itself, and/or our own replacement mainloop (which has its own major problems). (I'm aware that a separate crate exists adding a futures layer, but I was not at all impressed when I looked at it, since it seemed to ignore various details that should not be ignored to do things properly/safely).

`Arc` itself is a mutable reference and using an `Arc` wrapped object in multiple threads is only safe because the `Arc` wrapper forces us to open a hidden lock to get at the data it points to. The usual model in Rust is to have locks wrapping data like this, which fits neatly with the other aspects of the language and its safety features. However the traditional model of having locks alongside data is still perfectly valid design and more suitable in some cases, even if it goes against the grain in how you become used to typically doing things in Rust. It is necessary here with the threaded mainloop. Just because something does not feel "natural" doesn't mean it's wrong, we must choose the most suitable solution for each given situation. Here we must make careful use of the mainloop's lock in order to safely control access to objects between the user thread and the thread that runs the mainloop and (most) callback execution. You *can* use `Arc` instead of `Rc` to make things feel a little more natural and I believe in fact to get around the ugliness of this unsafe borrow checker pointer "hack", but this adds a completely unnecessary extra layer of locks and thus pointless inefficiency. Additionally when you have multiple locks involved then you need to worry about lock/unlock ordering to avoid deadlocks.

> ... so it's kinda weird to me to assume that people using this crate (who aren't necessarily experts) will naturally find this workaround ...

I *don't* expect users to have to find this discussion in order to know how to make use of the crate, quite the opposite, I expect them to learn how to do such basic things from the documentation. As I've said before, I'm open to patches / detailed feedback for problem areas in the documentation where new users have trouble.

> ... and to just close this issue

The issue as it was originally described was interpreted as the user pointing out a possible design flaw in terms of not being able to setup a callback due to borrow checker constraints, due to possibly lacking understanding in the area of the threaded mainloop lock, and not having understood from the documentation how to use it and the pointer technique to get around the borrow checker when using `Rc`. Having given some explanation and guidance I felt their problem was suitably addressed, thus I closed the issue. The follow up comment of not being able to do things without involving a small `unsafe` block and that it would be nice if possible for the context to be passed as a context I responded to by advising that `unsafe` blocks are not to be so afraid of, and that not providing the context as a param had been a deliberate design decision, though I could not recall the details at the time. The discussion thus ended. There was no basis there to reopen.

If you wish to open a new issue to highlight specific parts of the documentation which fail to explain things suitably, you're very welcome to do so and I'll do my best to try to resolve those problems if/when I can find the time. I'm afraid though that the lack of context param for this callback is going to have to remain so due to the above design constraints.

> Another disadvantage of deviating from the API in that way is that the C examples of how to use the pulse API become a bit useless because they all make heavy use of the `context` as the first parameter (e.g. [pavucontrol](context_state_callb)).
> 
> My use case is just gathering some configurational info, so I don't even want to do anything with the mainloop afterwards and instead just print out things on the `READY` state change. I didn't manage to get it to work though when I tried to extract the closure to a separate function, so sorry for being a bit frustrated.

That sounds a little like you might possibly be making some bad design decisions. I'm not sure what you mean exactly by "afterwards"; just destroy it once you're done, or are you trying to avoid using/starting a mainloop? Even if you're just wanting to use introspection functions to check details of the system, you still need the mainloop up and running as I recall. Most interaction with the PulseAudio service from your client application take place asynchronously and require the mainloop to be up and running to receive and react to messages the service sends to your client. It's not just needed for pumping audio data.

I'd advise that you don't try to do too much in each callback. With respect to your context callback in my opinion it really should be limited to just a mechanism for pausing your application thread until the context is ready for it to proceed. Your data gathering code should not be a part of it. That should be a separate block of code that runs in your user thread *after* the code dealing with waiting for the context to become ready. Specifically, assuming you're using the threaded mainloop for efficiency, you should set up your context state callback to simply execute the `signal()` mainloop function in case of 'ready', 'failed' or 'terminated' states, nothing more; having set that up, you lock the mainloop, start it, and then in an infinite loop (to catch false wakeups) you check the context state, and if it's 'ready', you break out of the loop and continue doing whatever (setup a stream, make an introspection query, whatever), if it's 'failed' or 'terminated' you unlock the mainloop, stop it, print an error and quit, and if it's anything else, you call the mainloop `wait()` function. Thus your app thread efficiently waits (including giving up the lock) for a wakeup signal from your callback to indicate change of state to ready/failed/terminated (which causes the lock to be regained whilst given up on the callback side), and you then respond accordingly, or go back to sleep if some other unexpected state.

If you're having problems, you can create an issue here to see if I can help (though I have a lot on my plate and no income to support myself in general currently let alone my work on this project). Otherwise you might find help on the PulseAudio mailing list perhaps, or places like stackoverflow, as I'm sure you probably already know about.

**Comment by lukasjuhrich** [comment]
@jnqnfe I just wanted to say thank you for typing all this up instead of shrugging it off. I still have a lot to learn when it comes to low-level programming, and your pointers are much appreciated!
