### ISSUE TITLE
Potential unsafety in context?

### ISSUE THREAD

**Issue by jD91mZM2** [jnqnfe/pulse-binding-rust#27]
The [Context](https://docs.rs/libpulse-binding/2.13.0/libpulse_binding/context/struct.Context.html#method.set_state_callback) struct can be connected to an event loop and triggered from a separate thread. Passing in thread-unsafe values here would result in a potential data race, right? So it should probably set the generic bounds `Box<dyn FnMut() + 'static + Send>`?

**Comment by jnqnfe** [comment]
Hi, sorry for the delayed response. I did take note of it a couple days ago but I've not been able to work on it yet beyond reading your message. My immediate reaction was that I was not at all sure where it was within the codebase you are suggesting needs such an adjustment, nor get my head around the concept of your description. Perhaps I just need to take a little time to get my head backin to this properly to understand, but I just suddenly remembered this now and thought it prudent to request some clarification in advance of spending further time on it :)

**Comment by jD91mZM2** [comment]
Hi! Example usage is in the old [xidlehook](https://gitlab.com/jD91mZM2/xidlehook/blob/e508fd8441ad8336fbbcc0870f8ed06d0f465c2e/src/pulse.rs#L46) source code. I was recently scanning through the code and realized all the `Rc`s that are being `move`d into the lambdas should not be usable here since the context is being polled from a separate thread.

[Context can be initialized](https://docs.rs/libpulse-binding/2.13.0/libpulse_binding/context/struct.Context.html?search=#method.new) with a [threaded mainloop](https://docs.rs/libpulse-binding/2.13.0/libpulse_binding/mainloop/threaded/struct.Mainloop.html) (with no `unsafe` rust code, on top of that)

Now, one solution would be to add a `Send` bound to all of context's callback functions. But then again, that'll also put unnecessary restrictions on single-threaded main loops... Tricky stuff.

**Comment by jnqnfe** [comment]
Again, apologies for the delayed response; I've finally been able to take a proper look at this today. Thanks for the clarification.

Firstly, as you correctly point out, it is problematic to add a `Send` constraint as described since it would negatively impact non-threaded use cases.

Now, I have looked at your use of the binding in xidlehook and there are indeed safety concerns as you noticed, however it is actually an issue in *use* of the binding in xidlehook rather than with the binding itself. You're not using the mainloop locking mechanism!!

In Rust we typically use wrappers such as `Arc` around data, however this thread-safe access model is not always possible/suitable/feasible and we must fall back to a lock that sits alongside the data which you have to remember to make use of to safely use the data it is meant to protect. The binding is forced to make use of such a design with the threaded mainloop. You've overlooked this lock.

The threaded mainloop takes its lock prior to executing callbacks. Callbacks are typically executed only by the mainloop thread, however in some cases are executed immediately in the currently thread. Through use of the mainloop lock in your own thread, you ensure that only one of the two threads are making use of the PA objects (or other objects you also only use behind the lock) are only used in one of these two threads in any given moment. Note that `Rc` is used in the binding examples rather than `Arc` for efficiency, since the locking is already taken care of separately.

Take a look at the usage example at the end of the module-level documentation of the bindings `mainloop::threaded` module.

Notice in comparison to your usage:
 1) The fact that `lock()` is called before calling `start()`
 2) The way in the example in which it waits for the context state to be signalled after starting, before acting upon whether it is then ready or failed, and protecting against unexpected wakeups
 3) It then removes the context state callback now no longer being interested in further changes
 4) You can make use of `borrow_mut()` outside of the callback definition towards the end of your `new()` function, contrary to your comment block there (such use compiles fine form me in the case of the documentation example)

If I were you, I would avoid setting up callbacks in the nested fashion you're doing so. I can see that you might be viewing it from a callback chain perspective, but the nesting goes against the "separation of concerns" principle imo and makes things overly complex to read. I think it would be clearer to separate it out so that obtaining the info follows on from dealing with context state, in the same way that chaining is adding something to the end, something that happens "next" rather than nesting stuff, if you follow my thoughts here...

Note that due to what I said about the locking mechanism of the mainloop protecting more than just PA objects, you could actually replace the `Arc` on your `counter` var with `Rc` to be more efficient. Once you've actually got the mainloop locking in place of course.

I'll close this now since it's an xidlehook issue...

**Comment by jD91mZM2** [comment]
Thank you for the insight! I'll try my best to follow your advice :)
So it doesn't bother you that it's possible to get data races with almost zero `unsafe` code?

> You can make use of borrow_mut() outside of the callback definition towards the end of your new() function, contrary to your comment block there (such use compiles fine form me in the case of the documentation example)

It's not that it compiles wrong, it's that it panics with
```
thread 'main' panicked at 'already mutably borrowed: BorrowError', src/libcore/result.rs:1165:5
```
. This doesn't happen in the examples as you use `unsafe { (*context_ref.as_ptr()).<function here>() }` inside all the callbacks.

--------------

Anyway, for using the locks, do you mean just doing something like
```rust
main.lock();
main.start().map_err(|err| format!("pulseaudio: {}", err))?;
main.unlock();
```
? Or do you want me to lock inside the callbacks as well?

**Comment by jnqnfe** [comment]
> So it doesn't bother you that it's possible to get data races with almost zero `unsafe` code?

Not really. In principle I would not be happy with such things, but some designs just are not compatible with the model of wrapping race-safe accessors around data, requiring falling back to the way we always did things back in C. I love Rust, it improves things a lot from where we were with C, but while it encourages us to move to the wrapper model, we cannot just assume that this model is always used in every part of every library. We as users of libraries have to take care to note what model is used to protect the data objects we create and use when threading is involved and use it appropriately. It simply is not feasible to design something to throw an error with the non-wrapper model to automatically point out unsafe usage. There is nothing particularly feasible to be done in this library to prevent such unsafe usage. It would involve either a complete separation of a thread-based and non-thread-based set of types disallowing mixing, or some sort of mainloop-locked object to pass into absolutely everything as a means of proving that you've got it locked when necessary, or objects being created from such a lock object and thrown away when unlocking. A complete nightmare in otherwords.

As long as documentation is read and the mechanism understood, there should be no problem is user code, and as already stated, there's not much that can be done to ensure mistakes are not made, with the exception of making documentation more clear if it is at all unclear.

> . This doesn't happen in the examples as you use `unsafe { (*context_ref.as_ptr()).<function here>() }` inside all the callbacks.

Oh, right, so I am :)

> Anyway, for using the locks, do you mean just doing something like
> 
> ```rust
> main.lock();
> main.start().map_err(|err| format!("pulseaudio: {}", err))?;
> main.unlock();
> ```

yes.

> ? Or do you want me to lock inside the callbacks as well?
> 
> EDIT: Published all my changes to a [pulseaudio-fix](https://gitlab.com/jD91mZM2/xidlehook/commits/pulseaudio-fix) branch

no, don't lock inside of the callbacks. this is at least wrong and at worse will cause a lock up if the recursive property of the underlying lock is changed (or documentation wrong about it actually being recursive - lifted from the underlying C documentation). the internal PA mainloop thread takes the lock itself behind the scenes before executing callbacks. where callbacks are executed directly within your thread (as sometimes is done by the functions you provide the callbacks to), this must happen in your own thread after having taken the lock (which you must do before interacting with PA objects), or in limited cases during the setup portion of your code prior to calling `start()` on your mainloop.

**Comment by jD91mZM2** [comment]
One simple solution to make sure the user can't write unsafe code without using `unsafe`, would be to simply mark the threaded `start()` function as such :)

Anyway, right, so locks around the main loop being started. That won't magically make the variable thread-safe so I assume I'll have to lock the main loop also when accessing the thread-unsafe counter?

**Comment by jnqnfe** [comment]
> One simple solution to make sure the user can't write unsafe code without using `unsafe`, would be to simply mark the threaded `start()` function as such :)

it isn't just the mainloop::start() function which needs protecting though, it is literally **everything**. Once the threaded mainloop has started, **every** action (method call) touching a PA object needs to be done with the lock held, either explicitly as in the case of your own thread, or implicitly in the case of the mainloop thread (which takes and releases the lock itself as needed in the background, such as when running your callbacks). We would thus end up marking almost every method in the entire library as unsafe and then we're just no better off at all.

> Anyway, right, so locks around the main loop being started. That won't magically make the variable thread-safe so I assume I'll have to lock the main loop also when accessing the thread-unsafe counter?

again, **no**, the lock needs to be used for all PA object interaction! (and any other stuff you are deciding to allow to be a partof the lock's scope, such as your counter here - why introduce an additional lock via an `Arc` wrapper when a suitable non-wrapper type lock is already available!)

I've had a look at your updated xidlehook code earlier and revised it further myself, which I'll post [here](https://gitlab.com/jD91mZM2/xidlehook/issues/6)

**Comment by jD91mZM2** [comment]
> it isn't just the mainloop::start() function which needs protecting though, it is literally everything. Once the threaded mainloop has started, every action (method call) touching a PA object needs to be done with the lock held

Right, but you still can't get data races if you don't start the threaded main loop :)

> again, no, the lock needs to be used for all PA object interaction! (and any other stuff you are deciding to allow to be a partof the lock's scope, such as your counter here - why introduce an additional lock via an Arc wrapper when a suitable non-wrapper type lock is already available!)

I think you misunderstood me, what I'm talking about *is* the `Arc`s.

```rust
impl Module for NotWhenAudio {
    fn pre_timer(&mut self, _timer: TimerInfo) -> Result<Progress> {
        let players = self.counter.last_total.get(); // this line
        if players == 0 {
            Ok(Progress::Continue)
        } else {
            Ok(Progress::Abort)
        }
    }
}
```

The variable lookup being made in the line with the comment is referring to a variable being set inside the thread. Therefore, I need to use `lock()`, right?

> I've had a look at your updated xidlehook code earlier and revised it further myself, which I'll post here

Woah, that's very kind of you! The above code seems to be unchanged, interestingly enough, I can't tell if that's intentional or just an oversight. Massive thanks, I'll bring in your changes ASAP :)

**Comment by jnqnfe** [comment]
> Right, but you still can't get data races if you don't start the threaded main loop :)

sure, but fundamentally it's about being conscious as a programmer doing multi-threaded programming that there are two different race-protection models and not just assuming that the wrapper one that plays well with Rust's safety design is the one in use, at least when dealing with bindings to C libraries, and also reading documentation, and even if I made `start()` unsafe and plastered a big warning directly in its method docs there's no guarantee that it'd be noticed and understood. :/

> I think you misunderstood me, what I'm talking about _is_ the `Arc`s.
> 
> ```rust
> impl Module for NotWhenAudio {
>     fn pre_timer(&mut self, _timer: TimerInfo) -> Result<Progress> {
>         let players = self.counter.last_total.get(); // this line
>         if players == 0 {
>             Ok(Progress::Continue)
>         } else {
>             Ok(Progress::Abort)
>         }
>     }
> }
> ```
> 
> The variable lookup being made in the line with the comment is referring to a variable being set inside the thread. Therefore, I need to use `lock()`, right?
>
> Woah, that's very kind of you! The above code seems to be unchanged, interestingly enough, I can't tell if that's intentional or just an oversight. Massive thanks, I'll bring in your changes ASAP :)

yes, I think I overlooked it there. if you're trading the `Arc` wrapper protection on your counter object for the protection of the mainloop lock, then all use of the counter needs to be behind use of the lock. Of course you need to be careful about where you use the lock, i.e. inside vs. outside methods like the one you quoted, since as mentioned earlier, you want to be using the lock in your own thread, but not in callbacks, and avoiding recursive locking of that lock as I'm not certain that the PulseAudio docs are actually correct about it supporting recursion.
