### ISSUE TITLE
Record Stream never calls read callback.

### ISSUE THREAD

**Issue by Aurailus** [jnqnfe/pulse-binding-rust#36]
Hi! I'm trying to create a volume mixer in Rust using your library, and I'm having an issue related to monitor streams. I'm trying to create a peak monitor, roughly derived from [pavucontrol's C++ implementation](https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/blob/master/src/mainwindow.cc#L642), and as far as I can tell I've inputted the same properties faithfully to libpulse_binding, but the callback I supply to `set_read_callback` never triggers. None of the unwrap calls fail, and the program doesn't crash, I just get no response. I've tried querying synchronously using `readable_size` as well, and I only ever get `None`.

Side note -- when I was trying to debug I ran across `Stream::set_state_callback`, and I'm unsure how I'm actually supposed to use it. It doesn't pass the current state into the callback and I can't reference the stream from inside the callback as it's already being used outside of it, so I wasn't able to use it to help me test.

I'm a new Rust programmer, so if I'm making a simple mistake I'd really appreciate being pointed in the right direction. Thank you for your time, and this library! 

```
// These values are dynamic in the actual code.
let input_index = 1; 
let sink_index = 0;

let mut attr = BufferAttr::default();
attr.fragsize = 4;
attr.maxlength = u32::MAX;

let spec = Spec { channels: 1, format: Format::F32le, rate: 25 };
assert!(spec.is_valid());

// self.context is an Rc<RefCell<...>> of the context.
let mut s = Stream::new(&mut self.context.borrow_mut(), "Peak Detect", &spec, None).unwrap();
s.set_monitor_stream(index).unwrap();

let tx = self.channel.tx.clone();
s.set_read_callback(Some(Box::new(move |peak| println!("Peak! {}", peak))));

s.connect_record(Some(&sink_index.to_string().as_str()), Some(&attr),
	StreamFlagSet::DONT_MOVE | StreamFlagSet::ADJUST_LATENCY | StreamFlagSet::PEAK_DETECT).unwrap();

```

**Comment by Aurailus** [comment]
Update: I managed to call set_state in a state callback using `Rc<RefCell>`, and the state is `Failed`. Is there any way I can get further information from this to discover the nature of the failure?

**Comment by jnqnfe** [comment]
Hi! :)

> I've tried querying synchronously using `readable_size` as well, and I only ever get `None`.

Note that `None` actually indicates an error for this function (I'll fix the documentation to add the missing clarification). (The underlying C API uses a `(size_t) -1` return value to indicate error, which I translate to `None` indicating lack of information).

So since PulseAudio is returning an error when simply being asked how many bytes can be read, this seems to indicate there's a problem. (I should clarify that I built this without being an actual PulseAudio expert, so there's a limit to my ability to intuitively grasp what is going wrong for you here).

> Side note -- when I was trying to debug I ran across `Stream::set_state_callback`, and I'm unsure how I'm actually supposed to use it. It doesn't pass the current state into the callback and I can't reference the stream from inside the callback as it's already being used outside of it, so I wasn't able to use it to help me test.

As you seem to have figured out in your follow-up, you need to create a cloned `Rc` instance to give to the callback, as demonstrated in the usage examples in the mainloop documentation. You can then query the state with `get_state()`.

> ```rust
> let spec = Spec { channels: 1, format: Format::F32le, rate: 25 };
> ```

I'd replace the little-endian specific `Format::F32le` with `Format::FLOAT32NE` (the native endian associated constant) for greater flexibility and avoidance of mistakes, just as pavucontrol does.

> Update: I managed to call set_state in a state callback using `Rc<RefCell>`, and the state is `Failed`. Is there any way I can get further information from this to discover the nature of the failure?

Unfortunately I don't think that there is, no. You say that the `unwrap()` calls are not failing, so thus an error code is not being returned from the functions you're calling. I'm not aware of any means of getting a direct explanation for why the state has ended up as failed. (Though you could try getting PulseAudio to output debug info to a log file and see if there's anything at all useful in that maybe, but I would not get my hopes up on that front).

The fact that it is failed is obviously another clear indicator that something is wrong though.

Perhaps it's worth checking that a basic playback example connects successfully if you've not already tried that?

> Another small update: I realized sinks actually have proper names, so I tried putting the sink's real name as the first argument of `connect_record` instead of the index, and it still didn't work.

Since pavucontrol itself is converting the index number to a string and using that as the device name, I'd assume that doing so is the correct thing to do.

Whether or not the indexes you are using are correct though is a whole different matter, and could very well be the cause of failure for all I know.

> ... but the callback I supply to `set_read_callback` never triggers.

The most obvious cause of callbacks never firing is because they've not been given a chance to. Note that callbacks are executed by the mainloop, and can only be executed when the mainloop is given opportunity to run. Are you allowing the mainloop to run after you've created and connected the stream?

Hmm, actually, you did say that you'd gotten the stream state callback working, so that suggests that you are indeed already giving the mainloop opportunity to run...

I'd suggest that the facts of the failed state, the error returned when doing a read-size check, and the lack of read callback execution all indicate that something is very wrong, either perhaps with your context or mainloop being incorrectly set up or becoming broken at some point prior to your checking things, or simply with what you're asking PulseAudio to do, such as pointing it at the wrong indexes, or not having a suitable stream available to be read?

I don't think that there's anything more I can say to try and help at this point. Perhaps it might help if you tried stripping down the pavucontrol C++ code (which presumably works fine) to a bare minimal working example of the monitor functionality and compare that with your actual Rust codebase. If you experience the same issues with a stripped down C++ code then you'll need to ask the PulseAudio experts on the PulseAudio mailing list.

If you want to send me a copy of the full application code to have a look at, you're welcome to. You can email it to me privately if you wish. To avoid an increase in spam I'll refrain from writing my email address here, but it's just a gmail account with the same username as here ;)

**Comment by Aurailus** [comment]
Thank you for your detailed response! I've had some luck creating monitors by passing None into the source name, which indicates that I probably have an incorrect value being passed into it in my main code, like you suggested. I'll have to look into it more on my own. Thanks! :)

**Comment by Aurailus** [comment]
Hi, so I figured it out, I was using the wrong index. Apparently `monitor_index` is separate from `index`. The more you know. I'll close this issue now.

Also -- I meant to ask you before I committed publicly but forgot (sorry!), but I credited you in my [application](https://Aurailus/Myxer) because without this library, I wouldn't have been able to make it. Right now I just used the name that you use on crates.io, but if you'd like me to change it to something else or remove it, I will, just let me know. Thanks for making this library!

**Comment by jnqnfe** [comment]
> Hi, so I figured it out, I was using the wrong index. Apparently `monitor_index` is separate from `index`. The more you know. I'll close this issue now.

Ok :+1: 

> Also -- I meant to ask you before I committed publicly but forgot (sorry!), but I credited you in my [application](https://Aurailus/Myxer) because without this library, I wouldn't have been able to make it. Right now I just used the name that you use on crates.io, but if you'd like me to change it to something else or remove it, I will, just let me know.

No problem, I don't mind at all. I'm not at all fussed whether you keep or remove it. Thank you though.

> Thanks for making this library!

You're very welcome :)
