### ISSUE TITLE
Assertion 'q->front' failed at pulsecore/queue.c:81, function pa_queue_push(). Aborting. Aborted (core dumped)

### ISSUE THREAD

**Issue by Aurailus** [jnqnfe/pulse-binding-rust#37]
Sometimes, when running a program I'm developing with libpulse-binding, I get the following error in the terminal:
```
Assertion 'q->front' failed at pulsecore/queue.c:81, function pa_queue_push(). Aborting.
Aborted (core dumped)
```
Unfortunately, I can't seem to get any more information, since no stack traces are given, even when the flag is enabled.
A quick google search results in [this issue](https://github.com/OpenRCT2/OpenRCT2/issues/3553), which suggests that the bug may have been fixed in a newer version of PulseAudio.
I was wondering if that's something that would need to be changed on your end, or on mine, and if so, what would have to be done? It seems that on other devices, this error will sometimes pop up randomly during the runtime of the application.

**Comment by jnqnfe** [comment]
Hi again. I don't suspect any bug in the binding at this time.

The issue you linked to, as you point out, suggests that perhaps this was due to a bug in PulseAudio itself and could be fixed by upgrading to a newer version, however they don't seem to have determined this with any certainty. I'd ask here what version of PulseAudio you have on these systems, however there's another possible cause...

Doing a little research myself for your error led me to [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1210049) where such errors were being encountered, which led to [this fix](https://github.com/FreeRDP/FreeRDP/pull/2694). In this case the cause was due to a failure to make proper use of the threaded mainloop lock.

This could very well be the cause of your problem also, assuming that you are using the threaded mainloop. Failure to use the lock is an easy mistake to make, with no compile time or run time errors to point out mistakes. It also fits with the randomness - both your application thread and the background PulseAudio threaded-mainloop thread modifying objects at the same unpredictable time due to the application thread having failed to grab the lock to get exclusive access when it needs to.

**Comment by Aurailus** [comment]
> This could very well be the cause of your problem also, assuming that you are using the threaded mainloop.

This could very well be the issue. I'll investigate further and get back to you. Thanks for the reply!

**Comment by Aurailus** [comment]
You were right, I added some `lock()` and `unlock()` calls around all of the pulse calls, and it seems to have resolved the problem. Thanks again for being so helpful!

**Comment by jnqnfe** [comment]
> You were right, I added some `lock()` and `unlock()` calls around all of the pulse calls, and it seems to have resolved the problem. Thanks again for being so helpful!

Great. No problem. :)

Beware though that having them simply around all pulse binding function calls might not be entirely sufficient to achieve complete thread safety. You have to assess the possibility of concurrent access of **all** objects, both pulse ones and others, from the two threads - your app thread and the background pulse mainloop thread (within which your callbacks are run). Your app thread and the mainloop thread must never be allowed to touch any object at the same time, and so if you share some non-pulse object with a callback and thus with the mainloop thread, you must thus take care with it (use the lock) for as long as that callback - and thus the possibility of concurrent access - exists.

Note that the background mainloop thread automatically takes the lock at the start of each loop and releases it at the end, so your callbacks are always executed with the lock held by the thread running them. It is thus wrong to try to make use of the lock within callbacks. Only one thread can hold the lock at any given time, and trying to take the lock when it is already taken will cause the thread trying to take it to wait for it to be freed. While your app thread holds it, the mainloop thread is blocked from running another loop and thus execution of callbacks is blocked. Your app thread can only take the lock in between mainloop loops, and thus never in the middle of executing a callback. The lock thus provides control over when your app thread does work with objects and when the mainloop thread and callbacks it executes does.

Also, note that not every single pulse function call you ever make necessarily needs to be wrapped in lock-unlock calls. You need to consider the possibility of concurrent access in each case, in order to decide whether locking is needed in order to avoid introducing unnecessary inefficiency. So for instance everything done in your app thread before starting the mainloop does not require any locking. The mainloop and context objects should always be considered to be used by the mainloop thread, so locking will always be required after starting the mainloop for anything involving them. A stream is linked to the context and so working with a stream thus requires locking. Contrastingly, if you create a `Format`, `Spec` or `ChannelVolumes` object for instance, which just hold simple data, unless you share them with a callback, or have gotten a reference to one from a shared object or something, then you can obviously call methods on them freely without involving the lock, since you know that these object instances are confined entirely to your app thread.

Finally, note that lack of thread safety for an object may not always result in an error and crash like you experienced here, it may just cause rare, buggy behaviour. So don't dismiss the need to treat an object carefully just because you don't observe a clear problem. You must think carefully about the possibility of concurrent access of any and all objects in all threaded programs and use locking where appropriate.
