### ISSUE TITLE
get_str documentation inaccurate

### ISSUE THREAD

**Issue by chrysn** [jnqnfe/pulse-binding-rust#39]
The documentation of Proplist::get_str says:

> Will return None if the key does not exist or if data is not valid UTF-8.

However, the implementation performs `.to_string_lossy()`, returns Some(String) where the string just contains replacement characters.

I think the implementation behavior makes more sense than the documented one (If my soundcard is named b"Xpecial Audio \xff", I prefer to see "Xpecial Audio �" over "Unnamed card" or whatever the application makes of a None, just the documentation doesn't say that.

**Comment by jnqnfe** [comment]
Hi. Indeed the implementation performs `.to_string_lossy()` as you've noticed, and I can appreciate that on the surface this suggests that the documentation is wrong, however it's not; there's a flaw in your assessment. :)

The documentation reflects the behaviour of the underlying C API function. If the stored string is invalid UTF-8 then the underlying C API function returns a `NULL` pointer resulting in this function returning `None`, not a lossy conversion. We don't get a chance to try to return a lossy conversion. Thus the documentation is actually correct.

You might then wonder why `.to_string_lossy()` is used instead of `.to_str()`. This really is just because it avoids having to handle the `Result` wrapper of `.to_str()`. The `.to_string_lossy()` call in this function will always return an unmodified string.

Note that the C API `pa_proplist_sets()` function underlying `.set_str()` only accepts valid UTF-8, so thus the situation of invalid UTF-8 being encountered in retrieving strings really should never occur. It may be worth tweaking the documentation of this function to suggests that the invalid UTF-8 case is very unlikely to be encountered.

**Comment by jnqnfe** [comment]
> Note that the C API `pa_proplist_sets()` function underlying `.set_str()` only accepts valid UTF-8, so thus the situation of invalid UTF-8 being encountered in retrieving strings really should never occur. It may be worth tweaking the documentation of this function to suggests that the invalid UTF-8 case is very unlikely to be encountered.

Of course there is no 'type' property to distinguish different types of proplist entries and thus it is perfectly possible to incorrectly store arbitrary data with the generic `.set()` method and then try to read it as a string with `.get_str()`, which does present an easy way to encounter an invalid utf-8 based failure.

**Comment by chrysn** [comment]
My bad, should have looked at the C API more carefully. Thanks for the detailed response!
